const properties = [
	{
		id: 1,
		images: [
			'https://static.house.ge/HouseGe/0_1732c4f6-24e3-4bf0-b4c8-dea850b5bc6d.jpg',
			'https://static.house.ge/HouseGe/13_7d4763aa-345f-4a79-abd1-b53f008aa8f9.jpg',
			'https://static.house.ge/HouseGe/14_5a7e33cf-a84e-4ad6-9ccf-0ef71b9b467c.jpg',
			'https://static.house.ge/HouseGe/16_492a101b-4a44-46a2-a75d-a2b4a55e55d8.jpg',
		],
		details: {
			parking: 3,
			bathroom: 2,
			room: 3,
			garage: 0,
			dateAdded: '10.10.2022',
		},
		description: `  " ვილა ლისზე " ევროპულ სტანდარტებზე მორგებული, უმაღლესი ხარისხის საცხოვრებელი სახლი. (მშენებეარე) საუკეთესო მდებარეობა პანორამული ხედებით, თბილისიდან რამდენიმე წუთში, ეკოლოგიურად სუფთა გარემოში.
        გარემო, სადაც შეგიძლია შეიქმნა სიმყუდროვე და სიმშვიდე, იყო ქალაქთან ახლოს, ხმაურისა და გამონაბოლქვისგან შორს.    
        შენი კომფორტისთვის შექმნილი ადაპტირებული გარემო; სასწავლო და სამედიცინო დაწესებულებები ორი წუთის სავალ გზაზე.  
        4 საძინებელი, 4 სველი წერტილი, იზოლირებული სამზარეულო და მისაღები (შესაძლებელია გეგმარების ინდივიდუალურად შეთანხმება). ინდივიდუალური აივნები და ტერასა მესამე სართულზე.    
        ავტოფარეხი 99 კვ.მ;    
        პირველი სართული 99 კვ.მ;
        მეორე სართული 119.8 კვ.მ; 
        მესამე სართული (ტერასა) 109.1 კვ.მ. 
        მიწის ნაკვეთი სრულად  359 კვ.მ.
        ეზო 260 კვ.მ.
        კარკასში შედის ალუმინის მუქი რუხი ფერის კარ-ფანჯარა, ალუმინის და შუშის კომბინირებული მოაჯირი, გარე ფასადის ყავისფერი აგურით მოპირკეთება. ასევე მთავარ შესასვლელში ჩაისმევა მეტალის კარი. სრულად მოეწყობა ეზო სადაც კოინდარის (ბალახის) სარწყავი არხები დაგეგმარდება.`,
		propertyType: 'კერძო სახლი',
		address: 'ლისი, თბილისი',
		location: 'თბილისი',
		transactionType: 'იყიდება',
		price: 300000,
		area: 392.8,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: false,
			washingMachine: true,
			basement: true,
			garage: false,
			furniture: true,
			alarm: false,
			tv: false,
			cableTv: true,
			internet: true,
			closet: true,
			balcony: true,
			fridge: true,
			centralHeating: true,
		},
		publisher: {
			name: 'სანდრო შერმადინი',
			number: '527880040',
		},
	},
	{
		id: 2,
		images: [
			'https://dam-assets.au.reastatic.net/images/w_800,h_450/v1668126688/news-lifestyle-content-assets/wp-content/production/capi_6a9209db8042bcbf5ae338f665f003d9_f78687becc629edcd748a099ae4774a3/capi_6a9209db8042bcbf5ae338f665f003d9_f78687becc629edcd748a099ae4774a3.webp?_i=AA',
			'https://dam-assets.au.reastatic.net/images/w_800,h_450/v1668126667/news-lifestyle-content-assets/wp-content/production/capi_6a9209db8042bcbf5ae338f665f003d9_72cad00054f51f367eaa6d04680838e4/capi_6a9209db8042bcbf5ae338f665f003d9_72cad00054f51f367eaa6d04680838e4.webp?_i=AA',
			'https://dam-assets.au.reastatic.net/images/w_800,h_450/v1668126684/news-lifestyle-content-assets/wp-content/production/capi_6a9209db8042bcbf5ae338f665f003d9_e26a77c3de92dd582b4782b008833397/capi_6a9209db8042bcbf5ae338f665f003d9_e26a77c3de92dd582b4782b008833397.webp?_i=AA',
			'https://dam-assets.au.reastatic.net/images/w_800,h_450/v1668126677/news-lifestyle-content-assets/wp-content/production/capi_6a9209db8042bcbf5ae338f665f003d9_59c7a5a9c58f528bbc954f7989bed0c5/capi_6a9209db8042bcbf5ae338f665f003d9_59c7a5a9c58f528bbc954f7989bed0c5.webp?_i=AA',
			'https://dam-assets.au.reastatic.net/images/w_800,h_450/v1668126672/news-lifestyle-content-assets/wp-content/production/capi_6a9209db8042bcbf5ae338f665f003d9_75ab5c70c9a3facf54393fb29b86164f/capi_6a9209db8042bcbf5ae338f665f003d9_75ab5c70c9a3facf54393fb29b86164f.webp?_i=AA',
		],
		details: {
			parking: 5,
			bathroom: 7,
			room: 12,
			garage: 2,
			dateAdded: '11.10.2022',
		},
		description: `იყიდება 119 წლის წინ აშენებული სასახლე წყნეთში. უნიკალური ავეჯით, დეკორით და ბაღით.`,
		propertyType: 'კერძო სახლი',
		address: 'წყნეთი',
		location: 'წყნეთი',
		transactionType: 'იყიდება',
		price: 3500000,
		area: 700,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: true,
			washingMachine: true,
			basement: true,
			garage: true,
			furniture: true,
			alarm: true,
			tv: true,
			cableTv: true,
			internet: true,
			closet: true,
			balcony: true,
			fridge: true,
			centralHeating: true,
		},
		publisher: {
			name: 'ალექსანდრე ამილახვარი',
			number: '527803244',
		},
	},
	{
		id: 3,
		images: [
			'https://static.my.ge/myhome/photos/2/8/7/2/7/large/12272782_1.jpg?v=9',
			'https://static.my.ge/myhome/photos/2/8/7/2/7/large/12272782_2.jpg?v=9',
			'https://static.my.ge/myhome/photos/2/8/7/2/7/large/12272782_4.jpg?v=9',
			'https://static.my.ge/myhome/photos/2/8/7/2/7/large/12272782_6.jpg?v=9',
		],
		details: {
			parking: 1,
			bathroom: 1,
			room: 2,
			garage: 0,
			dateAdded: '11.10.2022',
		},
		description: `ინოვაციური პროექტი  „კრწანისი რესორტ რეზიდენსი“ მრავალფუნქციური უბანია, რომელიც საცხოვრებელ ზონასთან ერთად, საგანმანათლებლო, სპორტულ, სარეკრეაციო და გასართობ ინფრასტრუქტურას მოიცავს.
		„კრწანისი რესორტ რეზიდენსი“ ქვეყნის დეველოპერული სექტორის ყველაზე მსხვილი პროექტია, ვინაიდან მისი ჯამური ღირებულება 200 მლნ. დოლარს შეადგენს. 
		   კრწანისი რესორტ რეზიდენსში თქვენ დაგხვდებათ: საცურაო აუზები(ღიადახურული) ფიტნეს დარბაზები ჩოგბურთის ფეხბურთის კალათბურთის მოედნები გოლფის მოედანი საჯინიბო ბოულინგ კლუბიბოქსის დარბაზები პინგპონგი ქვიშის ფრენბურთი საბილიარდო ჰიპერმარკეტი კაფერესტორნები სკოლა და ბაღი რაც მთავარია: შიდა ტერიტორიაზე გადაადგილება შესაძლებელი იქნება მხოლოდ გოლფის მანქანებით, საფეხმავლო ბილიკებით`,
		propertyType: 'ბინა',
		address: 'კრწანისი, მთაწმინდის რაიონი, თბილისი',
		location: 'კრწანისი',
		transactionType: 'იყიდება',
		price: 514800,
		area: 107.9,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: false,
			washingMachine: false,
			basement: true,
			garage: false,
			furniture: false,
			alarm: false,
			tv: false,
			cableTv: false,
			internet: false,
			closet: true,
			balcony: true,
			fridge: false,
			centralHeating: true,
		},
		publisher: {
			name: 'კრწანისი ვივა რეზიდენსი',
			number: '527787812',
		},
	},
	{
		id: 4,
		images: [
			'https://static.house.ge/HouseGe/0_44c6421c-a3d1-4915-99da-b05410129e27.jpg',
			'https://static.house.ge/HouseGe/13_7d4763aa-345f-4a79-abd1-b53f008aa8f9.jpg',
			'https://static.house.ge/HouseGe/8_1f35cf8b-dfeb-400a-9c8b-ac3ba2c70429.jpg',
			'https://static.house.ge/HouseGe/17_968c2efa-e788-4bd3-ae6b-fa63debad250.jpg',
		],
		details: {
			parking: 3,
			bathroom: 2,
			room: 3,
			garage: 0,
			dateAdded: '10.10.2022',
		},
		description: ` GWG ბათუმის შექმნა სრულიად ახალი თავგადასავალია . ჩვენი მიზანი იყო შეგვექმნა მრავალფუნქციური საცხოვრებელი კომპლექსი, რომელიც გააერთიანებდა თანამედროვე სტილს და ტრადიციულ დიზაინს, როგორც თითოეული ბინის ინტერიერისთვის, ასევე ექსტერიერისთვის.
		GWG- ის შექმნით, ქართველმა და ევროპელმა პროფესიონალებმა მიზნად დაისახეს შემოეტანათ საუკეთესო ევროპული ინოვაციები და ტექნოლოგიები ქართული უძრავი ქონების ბაზარზე. პროექტი შექმნილია ადგილმდებარეობის, გარემოს და ურბანული დაგეგმარების საფუძველზე, რომელიც აერთიანებს ტრადიციულს და თანამედროვეს.`,
		propertyType: 'ბინა',
		address: 'ბათუმი, ლორთქიფანიძის 30',
		location: 'ბათუმი',
		transactionType: 'იყიდება',
		price: null,
		area: 68.89,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: false,
			washingMachine: true,
			basement: true,
			garage: false,
			furniture: true,
			alarm: false,
			tv: false,
			cableTv: true,
			internet: true,
			closet: true,
			balcony: true,
			fridge: true,
			centralHeating: true,
		},
		publisher: {
			name: 'GWG Development',
			number: '551033311',
		},
	},
	{
		id: 5,
		images: [
			'https://static.house.ge/HouseGe/8_03f3a727-ed78-4740-9109-f1e28d386a7b.jpg',
			'https://static.house.ge/HouseGe/8_5c13b4ea-f88a-4e55-a2e9-02044a8282c6.jpg',
			'https://static.house.ge/HouseGe/16_a6726938-7a37-4110-b7d2-a92e9e76250e.jpg',
			'https://static.house.ge/HouseGe/15_86a77505-34e1-4803-b0b3-caedcca716d7.jpg',
			'https://static.house.ge/HouseGe/19_56b1df0f-a948-4659-abbe-809b79c428e7.jpg',
		],
		details: {
			parking: 2,
			bathroom: 2,
			room: 5,
			garage: 1,
			dateAdded: '12.10.2022',
		},
		description: `ჩაბარება მოხდება 2024-წლის სექტემბერში`,
		propertyType: 'ბინა',
		address: 'თბილისი, მირზა შაფის ქუჩა',
		location: 'თბილისი',
		transactionType: 'იყიდება',
		price: null,
		area: 512.7,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: false,
			washingMachine: true,
			basement: true,
			garage: true,
			furniture: true,
			alarm: true,
			tv: false,
			cableTv: true,
			internet: true,
			closet: true,
			balcony: true,
			fridge: true,
			centralHeating: true,
		},
		publisher: {
			name: 'Kings Garden',
			number: '575778877',
		},
	},
	{
		id: 6,
		images: [
			'http://www.rentals.ge/photos.php?ID=21031_3&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21031_4&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21031_5&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21031_6&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21031_8&x=800&y=750',
		],
		details: {
			parking: 1,
			bathroom: 1,
			room: 2,
			garage: 0,
			dateAdded: '12.10.2022',
		},
		description: `მყუდრო და ჰიპსტერული სახლი სოლოლაკში`,
		propertyType: 'ბინა',
		address: 'თბილისი, ქიქოძე',
		location: 'სოლოლაკი',
		transactionType: 'ქირავდება',
		price: 2500,
		area: 107,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: false,
			washingMachine: true,
			basement: true,
			garage: false,
			furniture: true,
			alarm: true,
			tv: false,
			cableTv: true,
			internet: true,
			closet: true,
			balcony: true,
			fridge: true,
			centralHeating: true,
		},
		publisher: {
			name: 'RENTALS LTD',
			number: '032454599',
		},
	},
	{
		id: 7,
		images: [
			'http://www.rentals.ge/photos.php?ID=21733_1&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21733_4&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21733_5&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21733_9&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21733_10&x=800&y=750',
		],
		details: {
			parking: 0,
			bathroom: 1,
			room: 3,
			garage: 0,
			dateAdded: '12.10.2022',
		},
		description: `3 ოთახიანი მყუდრო აპარტამენტი საუკეთესო ლოკაციაზე`,
		propertyType: 'ბინა',
		address: 'თბილისი, მთაწმინდა',
		location: 'თბილისი',
		transactionType: 'ქირავდება',
		price: 1800,
		area: 130,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: false,
			washingMachine: true,
			basement: true,
			garage: false,
			furniture: true,
			alarm: true,
			tv: false,
			cableTv: true,
			internet: true,
			closet: true,
			balcony: true,
			fridge: true,
			centralHeating: true,
		},
		publisher: {
			name: 'RENTALS LTD',
			number: '032454599',
		},
	},
	{
		id: 8,
		images: [
			'http://www.rentals.ge/photos.php?ID=21713_1&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21713_2&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21713_3&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21713_6&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21713_8&x=800&y=750',
		],
		details: {
			parking: 1,
			bathroom: 1,
			room: 2,
			garage: 0,
			dateAdded: '11.10.2022',
		},
		description: `2 საძინებლიანი აპარტამენტი ბალკონით რომელიც გადის ეზოში`,
		propertyType: 'ბინა',
		address: 'თბილისი, მცხეთის ქუჩა',
		location: 'ვაკე',
		transactionType: 'ქირავდება',
		price: 2500,
		area: 100,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: false,
			washingMachine: true,
			basement: true,
			garage: false,
			furniture: true,
			alarm: true,
			tv: false,
			cableTv: true,
			internet: true,
			closet: true,
			balcony: true,
			fridge: true,
			centralHeating: true,
		},
		publisher: {
			name: 'RENTALS LTD',
			number: '032454599',
		},
	},
	{
		id: 9,
		images: [
			'http://www.rentals.ge/photos.php?ID=19056_1&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=19056_4&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=19056_7&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=19056_9&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=19056_10&x=800&y=750',
		],
		details: {
			parking: 0,
			bathroom: 1,
			room: 1,
			garage: 0,
			dateAdded: '12.10.2022',
		},
		description: `სტუდიური ტიპის აპარტამენტი ქობულეთის ქუჩაზე`,
		propertyType: 'ბინა',
		address: 'ვაკე, ქობულეთის ქუჩა, თბილისი',
		location: 'ვაკე',
		transactionType: 'ქირავდება',
		price: 1500,
		area: 78,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: false,
			washingMachine: true,
			basement: true,
			garage: false,
			furniture: true,
			alarm: true,
			tv: false,
			cableTv: true,
			internet: true,
			closet: true,
			balcony: true,
			fridge: true,
			centralHeating: true,
		},
		publisher: {
			name: 'RENTALS LTD',
			number: '032454599',
		},
	},
	{
		id: 10,
		images: [
			'http://www.rentals.ge/photos.php?ID=21208_2&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21208_4&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21208_5&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21208_1&x=800&y=750',
		],
		details: {
			parking: 1,
			bathroom: 1,
			room: 3,
			garage: 0,
			dateAdded: '12.10.2022',
		},
		description: `ქირავდება 3 საძინებლიანი აპარტამენტი ვაკეში, რაზმაძის ქუჩაზე`,
		propertyType: 'ბინა',
		address: 'თბილისი, ვაკე, რაზმაძის ქუჩა',
		location: 'ვაკე',
		transactionType: 'ქირავდება',
		price: 5000,
		area: 250,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: false,
			washingMachine: true,
			basement: true,
			garage: false,
			furniture: true,
			alarm: true,
			tv: false,
			cableTv: true,
			internet: true,
			closet: true,
			balcony: true,
			fridge: true,
			centralHeating: true,
		},
		publisher: {
			name: 'RENTALS LTD',
			number: '032454599',
		},
	},
	{
		id: 11,
		images: [
			'https://gethome.ge/assets/uploads/homes/99198/429eb347d339919a30963f213db6670c43593.png',
			'https://gethome.ge/assets/uploads/homes/99198/062be325b27a6784e7bac93070cd6bcb50994.png',
			'https://gethome.ge/assets/uploads/homes/99198/062be325b27a6784e7bac93070cd6bcb15333.png',
			'https://gethome.ge/assets/uploads/homes/99198/062be325b27a6784e7bac93070cd6bcb87675.png',
		],
		details: {
			parking: 0,
			bathroom: 1,
			room: 3,
			garage: 0,
			dateAdded: '12.10.2022',
		},
		description: `იყიდება 3 ოთახიანი ბინა მთაწმინდაზე ფხოვის ქ 132m² საერთო ფართი 3 ოთახები 1 საძინებლები 3 /3 სართული აივანი/ლოჯია:2 სველი წერტილი:1 პროექტი:არასტანდარტული მდგომარეობა:ახალი რემონტით; სტატუსი:ახალი აშენებული ბუნებრივი აირი აივანი გარაჟი ცენტრალური გათბობა სისტემით და ყველა საჭირო კომუნიკაციით. პირველი დონის შესავლელიდან მეორეზე (მონო ფართი-რემონტის გარეშე (63.75მ2) ადის სპირალური კიბე. ბინა უცხოვრებელია. იყიდება დუპლექსის ტიპის ბინა საერთო ფართით 132მ2 ქალაქის ძალიან პრესტიჟულ, საუკეთესო ტურისტულ ზონაში, ახლად რესტავრირებულ ორბელიანის (კოლმეურნეობის) მოედანზე, „ალექსანდროვის ბაღის“ და პრეზიდენტის რეზიდენციის გვერდით საფეხმავლო ქუჩაზე, ხმაურისგან მოშორებით. სახლი ახალი აშენებულია "ძველი თბილისის ახალი სიცოცხლე" პროექტის ფარგლებში. ბინა გამოდგება როგორც სასტუმროდ, ასევე საოფისედ და საცხოვრებლად. მიწისქვეშა ავტომანქანის სადგომზე აქვს ორი უფასო ადგილი. ბინის პირველ დონეზე (68.5 მ2) განლაგებულია სტუდიოს ტიპის მისაღები ოთახი, საძინებელი, საგარდერობო ოთახი, ერთი სველი წერტილი, ორი აივანი.`,
		propertyType: 'ბინა',
		address: 'მთაწმინდა, ფხოვის ქუჩა',
		location: 'თბილისი',
		transactionType: 'იყიდება',
		price: 875000,
		area: 132,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: false,
			washingMachine: true,
			basement: true,
			garage: false,
			furniture: true,
			alarm: true,
			tv: false,
			cableTv: true,
			internet: true,
			closet: true,
			balcony: true,
			fridge: true,
			centralHeating: true,
		},
		publisher: {
			name: 'ნინო',
			number: '595151478',
		},
	},
	{
		id: 12,
		images: [
			'http://www.rentals.ge/photos.php?ID=21640_2&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21640_4&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21640_6&x=800&y=750',
			'http://www.rentals.ge/photos.php?ID=21640_7&x=800&y=750',
		],
		details: {
			parking: 1,
			bathroom: 1,
			room: 3,
			garage: 0,
			dateAdded: '12.10.2022',
		},
		description: `ქირავდება 3 საძინებლიანი აპარტამენტი ვაკეში, მცხეთის ქუჩაზე`,
		propertyType: 'ბინა',
		address: 'თბილისი, ვაკე, მცხეთის ქუჩა',
		location: 'ვაკე',
		transactionType: 'ქირავდება',
		price: 4000,
		area: 170,
		features: {
			naturalGas: true,
			IronDoor: true,
			hotWater: true,
			ac: true,
			telephone: false,
			washingMachine: true,
			basement: true,
			garage: false,
			furniture: true,
			alarm: true,
			tv: false,
			cableTv: true,
			internet: true,
			closet: true,
			balcony: true,
			fridge: true,
			centralHeating: true,
		},
		publisher: {
			name: 'RENTALS LTD',
			number: '032454599',
		},
	},
];

export default properties;
